//! Sidecars.
//!
//! - Debug builds: spawn from local source checkouts (api/anime-api, proxy,
//!   api/anivexa) so `git pull` in those folders takes effect immediately.
//! - Release builds: spawn the bundled binaries next to the app exe.
//!   Python sidecars are PyInstaller --noconsole builds (no window).
//!   Anivexa is spawned via std::process with CREATE_NO_WINDOW because
//!   tauri's sidecar() cannot pass window-creation flags and pkg always
//!   produces a console binary.
//!
//! The frontend talks to 127.0.0.1 — this only keeps the local
//! instances alive and reaps them on exit.
//!
//! Debuggability (for end users, not just devs):
//! - Every spawned child gets stdout/stderr appended to
//!   <app_log_dir>/<sidecar-name>.log (same folder Tauri itself uses).
//! - The PyInstaller entry (_kitawatch_entry.py, generated by
//!   build-sidecars.mjs) redirects its null stdout to the same folder when
//!   KITAWATCH_LOG_DIR is set.
//! - Launching the app with `--debug` keeps sidecar consoles visible and
//!   raises sidecar log verbosity to "info".
//! - Everything noteworthy at startup (missing exe, occupied port, spawn
//!   error) is recorded in STARTUP_NOTES and surfaced by the
//!   `collect_debug_report` command (Copy debug report in Settings).

use std::net::TcpStream;
use std::path::Path;
use std::path::PathBuf;
use std::process::Child;
use std::sync::{Mutex, OnceLock};
use std::time::Duration;
use tauri::Manager;

pub enum Proc {
    Dev(Child),
    #[cfg(not(debug_assertions))]
    Bundled(Child),
}

pub struct Sidecars {
    pub procs: Vec<(&'static str, Proc)>,
}

fn port_open(addr: &str) -> bool {
    match addr.parse() {
        Ok(a) => TcpStream::connect_timeout(&a, Duration::from_millis(400)).is_ok(),
        Err(_) => false,
    }
}

fn python() -> String {
    std::env::var("KITAWATCH_PYTHON").unwrap_or_else(|_| {
        if cfg!(windows) {
            "python".to_string()
        } else {
            "python3".to_string()
        }
    })
}

fn find_dir(env_var: &str, markers: &[&str]) -> Option<PathBuf> {
    if let Ok(dir) = std::env::var(env_var) {
        let p = PathBuf::from(&dir);
        if p.exists() {
            return Some(p);
        }
    }
    for cand in ["..", "../..", "."] {
        for marker in markers {
            let p = PathBuf::from(cand).join(marker);
            if p.exists() {
                return Some(p);
            }
        }
    }
    None
}

/// Target-triple suffix used by the sidecar build script (build:sidecars).
#[cfg(all(target_os = "windows", target_arch = "x86_64"))]
pub const SIDE_TRIPLE: &str = "x86_64-pc-windows-msvc";
#[cfg(all(target_os = "linux", target_arch = "x86_64"))]
pub const SIDE_TRIPLE: &str = "x86_64-unknown-linux-gnu";

/// `KitaWatch.exe --debug`: keep sidecar windows visible and bump log level.
pub fn debug_mode() -> bool {
    std::env::args().any(|a| a == "--debug" || a == "-d")
}

/// Where sidecar logs live: the app's own log dir (Tauri resolves it to
/// %LOCALAPPDATA%\com.kitawatch.app\logs on Windows), overridable via
/// KITAWATCH_LOG_DIR for portable setups.
pub fn log_dir<R: tauri::Runtime, M: Manager<R>>(app: &M) -> PathBuf {
    if let Ok(d) = std::env::var("KITAWATCH_LOG_DIR") {
        return PathBuf::from(d);
    }
    app.path()
        .app_log_dir()
        .unwrap_or_else(|_| std::env::temp_dir().join("kitawatch-logs"))
}

// ---------------------------------------------------------------------------
// Startup notes — collected so `collect_debug_report` can explain WHY a
// sidecar is missing (exe absent? port squatted? spawn failed?).
// ---------------------------------------------------------------------------

static STARTUP_NOTES: OnceLock<Mutex<Vec<String>>> = OnceLock::new();

fn note(msg: impl Into<String>) {
    let msg = msg.into();
    eprintln!("[kitawatch] {msg}");
    let notes = STARTUP_NOTES.get_or_init(|| Mutex::new(Vec::new()));
    if let Ok(mut n) = notes.lock() {
        n.push(msg);
    }
}

pub fn startup_notes() -> Vec<String> {
    STARTUP_NOTES
        .get()
        .and_then(|m| m.lock().ok().map(|n| n.clone()))
        .unwrap_or_default()
}

#[cfg(debug_assertions)]
mod imp {
    use super::*;
    use std::process::Command;

    fn spawn_uvicorn(dir: &PathBuf, app: &str, port: u16, logs: &Path) -> Option<Child> {
        match Command::new(python())
            .args(["-m", "uvicorn", app, "--host", "127.0.0.1", "--port", &port.to_string()])
            .env("KITAWATCH_LOG_DIR", logs)
            .current_dir(dir)
            .spawn()
        {
            Ok(child) => {
                eprintln!("[kitawatch] started sidecar {app} on 127.0.0.1:{port}");
                Some(child)
            }
            Err(e) => {
                note(format!("failed to start {app}: {e}"));
                None
            }
        }
    }

    fn spawn_node(dir: &PathBuf, script: &str, port: u16, logs: &Path) -> Option<Child> {
        match Command::new("node")
            .arg(script)
            .env("PORT", port.to_string())
            .env("KITAWATCH_LOG_DIR", logs)
            .current_dir(dir)
            .spawn()
        {
            Ok(child) => {
                eprintln!("[kitawatch] started sidecar {script} on 127.0.0.1:{port}");
                Some(child)
            }
            Err(e) => {
                note(format!("failed to start {script}: {e}"));
                None
            }
        }
    }

    pub fn start(app: &tauri::App) -> Vec<(&'static str, Proc)> {
        let mut procs = Vec::new();
        let logs = super::log_dir(app);

        if port_open("127.0.0.1:8000") {
            note("port 8000 already in use at launch — Kuhi sidecar NOT started (possible port conflict)");
        } else if let Some(dir) = find_dir("KITAWATCH_API_DIR", &["api/anime-api", "anime-api"]) {
            if let Some(c) = spawn_uvicorn(&dir, "api:app", 8000, &logs) {
                procs.push(("Kuhi API", Proc::Dev(c)));
            }
        } else {
            note("Kuhi API source not found — run `npm run setup:api`");
        }

        if port_open("127.0.0.1:8001") {
            note("port 8001 already in use at launch — proxy sidecar NOT started (possible port conflict)");
        } else if let Some(dir) = find_dir("KITAWATCH_PROXY_DIR", &["proxy"]) {
            if let Some(c) = spawn_uvicorn(&dir, "server:app", 8001, &logs) {
                procs.push(("proxy", Proc::Dev(c)));
            }
        } else {
            note("proxy/ source not found");
        }

        if port_open("127.0.0.1:4000") {
            note("port 4000 already in use at launch — Anivexa sidecar NOT started (possible port conflict)");
        } else if let Some(dir) = find_dir("KITAWATCH_ANIVEXA_DIR", &["api/anivexa", "anivexa"]) {
            if dir.join("server.js").exists() {
                if let Some(c) = spawn_node(&dir, "server.js", 4000, &logs) {
                    procs.push(("Anivexa API", Proc::Dev(c)));
                }
            } else {
                note("api/anivexa/server.js missing — run `npm run setup:anivexa`");
            }
        } else {
            note("Anivexa API source not found — run `npm run setup:anivexa` to enable it");
        }

        procs
    }
}

#[cfg(not(debug_assertions))]
mod imp {
    use super::*;
    use std::fs::OpenOptions;
    use std::process::{Command, Stdio};

    /// Resolve a bundled sidecar exe. Tauri installs externalBin files WITHOUT
    /// the target-triple suffix (it strips it at bundle time), so check the
    /// plain name first; the triple-suffixed variant is a fallback.
    fn bundled_exe(name: &str) -> Option<PathBuf> {
        let mut exe = std::env::current_exe().ok()?;
        exe.pop(); // drop kitawatch.exe -> install dir
        let ext = if cfg!(windows) { ".exe" } else { "" };
        let plain = format!("{name}{ext}");
        let tripled = format!("{name}-{SIDE_TRIPLE}{ext}");
        let candidates = [
            exe.join(&plain),
            exe.join(&tripled),
            exe.join("binaries").join(&plain),
            exe.join("binaries").join(&tripled),
        ];
        for path in &candidates {
            if path.exists() {
                return Some(path.clone());
            }
        }
        note(format!(
            "bundled sidecar missing: {plain} (checked {})",
            candidates
                .iter()
                .map(|p| p.display().to_string())
                .collect::<Vec<_>>()
                .join(", ")
        ));
        None
    }

    /// Spawn a child with stdout+stderr appended to <log_dir>/<name>.log and
    /// the env the PyInstaller entry needs to log too. Windowless unless the
    /// app was launched with `--debug`.
    fn spawn_logged(name: &str, logs: &Path, mut cmd: Command) -> Option<Child> {
        #[cfg(windows)]
        {
            use std::os::windows::process::CommandExt;
            const CREATE_NO_WINDOW: u32 = 0x0800_0000;
            if !debug_mode() {
                cmd.creation_flags(CREATE_NO_WINDOW);
            }
        }
        let _ = std::fs::create_dir_all(logs);
        let log_path = logs.join(format!("{name}.log"));
        match OpenOptions::new().create(true).append(true).open(&log_path) {
            Ok(file) => {
                // clone before moving into Stdio so both get the same fd offset
                let out = file.try_clone().ok()?;
                let err = file.try_clone().ok()?;
                cmd.stdout(Stdio::from(out)).stderr(Stdio::from(err));
            }
            Err(e) => note(format!("cannot open {log_path:?} for sidecar logs: {e}")),
        }
        cmd.env("KITAWATCH_LOG_DIR", logs)
            .env("LOG_NAME", name)
            .env("LOG_LEVEL", if debug_mode() { "info" } else { "warning" });
        match cmd.spawn() {
            Ok(child) => Some(child),
            Err(e) => {
                note(format!("failed to spawn sidecar {name}: {e}"));
                None
            }
        }
    }

    pub fn start(app: &tauri::App) -> Vec<(&'static str, Proc)> {
        let mut procs = Vec::new();
        let logs = super::log_dir(app);

        if !port_open("127.0.0.1:8000") {
            if let Some(exe) = bundled_exe("kitawatch-kuhi-api") {
                if let Some(c) = spawn_logged("kitawatch-kuhi-api", &logs, Command::new(exe)) {
                    eprintln!("[kitawatch] started bundled kuhi-api on 127.0.0.1:8000 (log: {})",
                        logs.join("kitawatch-kuhi-api.log").display());
                    procs.push(("Kuhi API", Proc::Bundled(c)));
                }
            }
        } else {
            note("port 8000 already in use at launch — Kuhi sidecar NOT started (possible port conflict)");
        }

        if !port_open("127.0.0.1:8001") {
            if let Some(exe) = bundled_exe("kitawatch-proxy") {
                if let Some(c) = spawn_logged("kitawatch-proxy", &logs, Command::new(exe)) {
                    eprintln!("[kitawatch] started bundled proxy on 127.0.0.1:8001 (log: {})",
                        logs.join("kitawatch-proxy.log").display());
                    procs.push(("proxy", Proc::Bundled(c)));
                }
            }
        } else {
            note("port 8001 already in use at launch — proxy sidecar NOT started (possible port conflict)");
        }

        if !port_open("127.0.0.1:4000") {
            if let Some(exe) = bundled_exe("kitawatch-anivexa") {
                let mut anivexa_cmd = Command::new(exe);
                anivexa_cmd.env("PORT", "4000");
                if let Some(c) = spawn_logged("kitawatch-anivexa", &logs, anivexa_cmd) {
                    eprintln!("[kitawatch] started bundled anivexa on 127.0.0.1:4000 (log: {})",
                        logs.join("kitawatch-anivexa.log").display());
                    procs.push(("Anivexa API", Proc::Bundled(c)));
                }
            }
        } else {
            note("port 4000 already in use at launch — Anivexa sidecar NOT started (possible port conflict)");
        }

        procs
    }
}

/// Windows: sidecars orphaned by a crashed/killed app (no graceful Exit
/// event) survive as zombie exes. Kill any leftovers before spawning fresh —
/// port probes alone can't see a hung process holding no listen socket.
#[cfg(target_os = "windows")]
fn kill_stragglers() {
    use std::process::{Command, Stdio};
    for name in [
        "kitawatch-kuhi-api.exe",
        "kitawatch-proxy.exe",
        "kitawatch-anivexa.exe",
    ] {
        let _ = Command::new("taskkill")
            .args(["/F", "/IM", name])
            .stdout(Stdio::null())
            .stderr(Stdio::null())
            .status();
    }
}

#[cfg(target_os = "linux")]
fn kill_stragglers() {
    use std::process::{Command, Stdio};
    for name in [
        "kitawatch-kuhi-api",
        "kitawatch-proxy",
        "kitawatch-anivexa",
    ] {
        let _ = Command::new("pkill")
            .arg("-f")
            .arg(name)
            .stdout(Stdio::null())
            .stderr(Stdio::null())
            .status();
    }
}

#[cfg(not(any(target_os = "windows", target_os = "linux")))]
fn kill_stragglers() {}

pub fn start(app: &tauri::App) -> Sidecars {
    kill_stragglers();
    // make sure the log dir exists even in dev, so the debug report and any
    // KITAWATCH_LOG_DIR-aware child always have a valid target
    let _ = std::fs::create_dir_all(log_dir(app));
    let procs = imp::start(app);
    Sidecars { procs }
}

pub fn stop(sidecars: &mut Sidecars) {
    for (name, proc) in std::mem::take(&mut sidecars.procs) {
        eprintln!("[kitawatch] stopping {name} sidecar");
        match proc {
            Proc::Dev(mut c) => {
                let _ = c.kill();
            }
            #[cfg(not(debug_assertions))]
            Proc::Bundled(mut c) => {
                let _ = c.kill();
            }
        }
    }
}